project:
  type: default
  
profile:
  default: chapters
  # output-dir: chapters
  # render:
  #   #- "intro.qmd"
  #   - L00_minimal_chapter.qmd

# pre-render:
# - quarto --version


bibliography: references.bib
csl: "_resources/templates/harvard-x.csl"
date-format: "DD.MM.YYYY"
lang: de-CH
#code-block-background: true      
#code-block-border-left: true
# callout-appearance: default
thanks: Thanks to the Quarto team for their great work on this project.
copyright: Pia Bereuter © 2024 
license: Diese Arbeit ist lizenziert unter [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"